apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gok8s
  name: gok8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gok8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gok8s
    spec:
      containers:
      - image: jaybarb1990/client-go:0.1.1
        name: client-go
        resources: {}
status: {}
